WareHouse/Controllers/StockController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WareHouse.Models;
using WareHouse.Models.Data;

namespace WareHouse.Controllers
{
    [Authorize]
    public class StockController : Controller
    {
        
    
        // GET
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

WareHouse/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WareHouse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand text-light" asp-area="" asp-controller="Stock" asp-action="Index">WareHouse</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <ul class="navbar-nav flex-grow-1 justify-content-start">
                        @if (User.IsInRole("user") && (User.Identity.IsAuthenticated))
                        {
                            
                            
                        }

                    </ul>
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        @if (User.IsInRole("user") && (User.Identity.IsAuthenticated))
                        {
                        
                            <li class="nav-item p-2"> 
                                <form method="get" asp-action="PersonalProfile" asp-controller="Profile"> 
                                    <input type="submit" class="btn btn-primary" value="Профиль"> 
                                 </form> 
                            </li> 
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item p-2">
                                <form method="post" asp-action="Logout" asp-controller="Account">
                                    <input type="submit" class="btn btn-info" value="Выход">
                                </form>
                            </li>
                            <li class="nav-item p-2">
                                <span class="nav-link text-light"> Hello, @User.Identity.Name</span>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item p-2">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                            </li>
                            <li class="nav-item p-2">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                            </li>
                        }

                    </ul>

                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; DjAvad  - <a asp-area="" asp-controller="Stock" asp-action="Index">на главную</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>